### ISSUE TITLE
Capstone Project Support Review

### ISSUE THREAD

**Issue by ometman** [AlierPM/bookify-frontend#21]
We are about completing the project both at the frontend and backend:
- The team include: @Izebiafe, @DevKaranJ, @AlierPM, @ometman and @the-faizmohammad 
- The team is repeating so we are implementing [This Project](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/buisness_requirements_2.md)
- All functionalities working except API Documentation and Add to Favorites
- Links to Project: [Frontend](https://github.com/AlierPM/bookify-frontend) and [Backend](https://github.com/AlierPM/bookify-backend)
- We also request clarity of requirements, including unit test for frontend, and anything missed
- The link to [Backend PR](https://github.com/AlierPM/bookify-backend/issues/8)

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!



- [ ] Kindly open a Pull Request pointing from dev to main instead of a GitHub issue.  The branch should contain the whole content of the project in order to be able to deliver a proper review.





#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------
